project:
  type: website
  output-dir: ../docs


website:
  search: true
  page-navigation: true
  page-footer:
    border: false
    background: transparent
    foreground: DimGray
    #left: Left content
    #right: Right content
  navbar:
    background: transparent
    pinned: true
    left:
      - file: "https://chaishekar.github.io/Portfolio/"
        text: Home
      - text: Introduction
        href: "index.qmd#intro"
      - text: "Data Management"
        menu: 
        - text: "Data Collection"
          href: "index.qmd#data-collection"
        - text: "Data Cleaning"
          href: "index.qmd#data-cleaning"
      - text: Analysis
        menu:
        - text: Exploratory Data Analysis
          href: "index.qmd#eda"
        - text: Natural Language Progessing
          href: "index.qmd#nlp"
        - text: Machine Learning
          href: "index.qmd#ml"
      - text: Conclusion
        href: "index.qmd#conclusion"
      - text: "Feedback"
        href: "feedback.qmd"


    right:
      - icon: github
        href: https://github.com/chaishekar/Taylor-TALK-Reddit-s-Taylor-Swift-Hub

        

format:
  html:
    theme: 
      - styles.scss
    toc: false

editor: visual

